//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayerCake.Kernel.Tenants.Projects {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectValidationMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectValidationMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LayerCake.Kernel.Tenants.Projects.ProjectValidationMessages", typeof(ProjectValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color is required.
        /// </summary>
        internal static string ColorRequired {
            get {
                return ResourceManager.GetString("ColorRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color must be a valid hex color code (e.g., #0d6efd).
        /// </summary>
        internal static string ColorInvalidFormat {
            get {
                return ResourceManager.GetString("ColorInvalidFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        internal static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description must be 300 characters or less.
        /// </summary>
        internal static string DescriptionMaxLength {
            get {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon is required.
        /// </summary>
        internal static string IconRequired {
            get {
                return ResourceManager.GetString("IconRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project key is required.
        /// </summary>
        internal static string KeyRequired {
            get {
                return ResourceManager.GetString("KeyRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project key must be 10 characters or less.
        /// </summary>
        internal static string KeyMaxLength {
            get {
                return ResourceManager.GetString("KeyMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project key can only contain uppercase letters and numbers.
        /// </summary>
        internal static string KeyInvalidFormat {
            get {
                return ResourceManager.GetString("KeyInvalidFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project name is required.
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project name must be 50 characters or less.
        /// </summary>
        internal static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project owner is required.
        /// </summary>
        internal static string OwnerIdRequired {
            get {
                return ResourceManager.GetString("OwnerIdRequired", resourceCulture);
            }
        }
    }
}
