import {
  LuFolder,
  LuStar,
  LuHeart,
  LuZap,
  LuTarget,
  LuTrendingUp,
  LuCode,
  LuDatabase,
  LuServer,
  LuCloud,
  LuShield,
  LuLock,
  LuUsers,
  LuUser,
  LuBriefcase,
  LuCalendar,
  LuClock,
  LuBell,
  LuMail,
  LuPhone,
  LuMapPin,
  LuSettings,
} from 'react-icons/lu'

export const icons = [
  { name: 'Folder', component: LuFolder },
  { name: 'Star', component: LuStar },
  { name: 'Heart', component: LuHeart },
  { name: 'Zap', component: LuZap },
  { name: 'Target', component: LuTarget },
  { name: 'TrendingUp', component: LuTrendingUp },
  { name: 'Code', component: LuCode },
  { name: 'Database', component: LuDatabase },
  { name: 'Server', component: LuServer },
  { name: 'Cloud', component: LuCloud },
  { name: 'Shield', component: LuShield },
  { name: 'Lock', component: LuLock },
  { name: 'Users', component: LuUsers },
  { name: 'User', component: LuUser },
  { name: 'Briefcase', component: LuBriefcase },
  { name: 'Calendar', component: LuCalendar },
  { name: 'Clock', component: LuClock },
  { name: 'Bell', component: LuBell },
  { name: 'Mail', component: LuMail },
  { name: 'Phone', component: LuPhone },
  { name: 'MapPin', component: LuMapPin },
  { name: 'Settings', component: LuSettings },
]

